### PR TITLE
Update Ruby + Dev Container Image to 2.4.1

### PR DESCRIPTION
**Pull request by bascht**
* Bump Ruby to `2.4.1p111`
* Build Docker image from `ruby:2.4.1`
* Use rake `12.0.0`
  (the Docker base image comes with 12 installed in
  /usr/local/bin/rake and shit will hit fan if we differ from that)
* Update RSpec to `3.4.4`
  Restores [compatibility with Rake 12](https://github.com/rspec/rspec-core/compare/v3.4.3...v3.4.4)
* Update therubyracer to `0.12.3`
  Adds [Ruby 2.4 compatibility](https://github.com/cowboyd/therubyracer/issues/430)
* Work around a few changes in the docker base image
  See changes [from 2.2 to to 2.3](https://github.com/docker-library/ruby/pull/68)

### CODE REVIEW

**Comment by moonglum** [comment]
@bascht Looking good so far. Any idea why the specs are failing?

**Comment by bascht** [comment]
@moonglum The radar specs failed, but that was probably because of [2.4 compat issues with webmock](https://github.com/bblimke/webmock/issues/683) – after upgrading webmock it still looks sketchy: 
```
 6) Radar::Meetup should get the next events for a meetup
     Failure/Error: json = JSON.parse(RubyMeetup::ApiKeyClient.new.get_path("/2/events", {group_urlname: group_urlname}))
     
     RuntimeError:
       401 Unauthorized
       {"details":"API requests must be key-signed, oauth-signed, or accompanied by a key: https:\/\/www.meetup.com\/meetup_api\/docs\/#authentication","code":"not_authorized","problem":"You are not authorized to make that request"}
     # /gems/gems/ruby_meetup2-0.5.0/lib/ruby_meetup.rb:72:in `block in get'
     # /gems/gems/ruby_meetup2-0.5.0/lib/ruby_meetup.rb:68:in `get'
     # /gems/gems/ruby_meetup2-0.5.0/lib/ruby_meetup.rb:58:in `get_path'
     # ./lib/radar/meetup.rb:9:in `next_events'
     # ./spec/lib/radar/meetup_spec.rb:11:in `block (3 levels) in <top (required)>'
     # /gems/gems/vcr-2.9.2/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /gems/gems/vcr-2.9.2/lib/vcr.rb:182:in `use_cassette'
     # ./spec/lib/radar/meetup_spec.rb:10:in `block (2 levels) in <top (required)>'

  7) Radar::Ical should get the next events for a meetup
     Failure/Error: ical = open(@radar_setting.url, &:read)
     
     OpenSSL::SSL::SSLError:
       SSL_connect returned=1 errno=0 state=error: certificate verify failed
     # ./lib/radar/ical.rb:9:in `next_events'
     # ./spec/lib/radar/ical_spec.rb:11:in `block (3 levels) in <top (required)>'
     # /gems/gems/vcr-2.9.2/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /gems/gems/vcr-2.9.2/lib/vcr.rb:182:in `use_cassette'
     # ./spec/lib/radar/ical_spec.rb:10:in `block (2 levels) in <top (required)>'

```

Are we smoke-testing a live API?

**Comment by moonglum** [comment]
Seems like it... I've never read the code for or used the Radar Feature 😨

**Comment by bascht** [comment]
@moonglum plot twist: We're testing the vimberlin website the whole time and their certificate ran out about 10 days ago. :joy:

Paging @wikimatze – TO THE LET'S ENCRYPT MOBILE!

**Comment by moonglum** [comment]
Ok, that was unexpected ^^

**Comment by wikimatze** [comment]
Ups, I thought the automatic certificate renewal would work ... I'll take care of it. What are you actually testing on vimberlin?

**Comment by bascht** [comment]
@wikimatze We're not actually testing the live page, but a [prerecorded session](https://github.com/hacken-in/hacken-in/blob/master/spec/fixtures/vcr_cassettes/vim_berlin_ical_feed.yml) – but the VCR gem was broken in our test & we accidentally tested the live website. :smile:

**Comment by wikimatze** [comment]
I see, the URL of vimberlin.de/vimberlin.ics is not there anymore.

**Comment by bascht** [comment]
@moonglum :bowing_man: thank you! One little tidbit: We currently cannot run `master` + `production` in different Ruby versions. :smiley_cat: So, I'd say we make a quick "ship it to both environments" merge + tag.

**Comment by moonglum** [comment]
Sounds great!

**Comment by bascht** [comment]
Switched Uberspace to `2.4.1` – let's see if we can merge / tag this right through. :rocket:

**Comment by bascht** [comment]
Brilliant.

```

Deploying application
Agent pid 19976
Identity added: config/travis/travis-deploy-key (config/travis/travis-deploy-key)
Using /home/travis/.rvm/gems/ruby-2.4.1
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching rake 10.3.2
Installing rake 10.3.2
Fetching i18n 0.7.0
Installing i18n 0.7.0
Fetching net-ssh 3.1.1
Installing net-ssh 3.1.1
Fetching chronic 0.10.2
Installing chronic 0.10.2
Using bundler 1.15.1
Fetching net-scp 1.2.1
Installing net-scp 1.2.1
Fetching whenever 0.9.4
Installing whenever 0.9.4
Fetching sshkit 1.9.0
Installing sshkit 1.9.0
Fetching capistrano 3.4.0
Installing capistrano 3.4.0
Fetching capistrano-bundler 1.1.4
Installing capistrano-bundler 1.1.4
Fetching capistrano-rails 1.1.6
Installing capistrano-rails 1.1.6
Bundle complete! 5 Gemfile dependencies, 11 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from capistrano:
Capistrano 3.1 has some breaking changes. Please check the CHANGELOG: http://goo.gl/SxB0lr

If you're upgrading Capistrano from 2.x, we recommend to read the upgrade guide: http://goo.gl/4536kB

The `deploy:restart` hook for passenger applications is now in a separate gem called capistrano-passenger.  Just add it to your Gemfile and require it in your Capfile.
INFO [0fb6c4a6] Running /usr/bin/env mkdir -p /tmp/hacken-in/ as hacken@dubhe.uberspace.de
/home/travis/.rvm/gems/ruby-2.4.1/gems/net-ssh-3.1.1/lib/net/ssh/transport/cipher_factory.rb:97: warning: constant OpenSSL::Cipher::Cipher is deprecated
/home/travis/.rvm/gems/ruby-2.4.1/gems/net-ssh-3.1.1/lib/net/ssh/transport/cipher_factory.rb:72: warning: constant OpenSSL::Cipher::Cipher is deprecated
INFO [0fb6c4a6] Finished in 3.430 seconds with exit status 0 (successful).
INFO Uploading /tmp/hacken-in/git-ssh.sh 100.0%
INFO [2b24c490] Running /usr/bin/env chmod +x /tmp/hacken-in/git-ssh.sh as hacken@dubhe.uberspace.de
INFO [2b24c490] Finished in 0.388 seconds with exit status 0 (successful).
INFO [e1f4e1bb] Running /usr/bin/env git ls-remote --heads https://github.com/hacken-in/website.git as hacken@dubhe.uberspace.de
INFO [e1f4e1bb] Finished in 1.038 seconds with exit status 0 (successful).
INFO [a244ff64] Running /usr/bin/env mkdir -p ~/hacken-in-master/shared ~/hacken-in-master/releases as hacken@dubhe.uberspace.de
INFO [a244ff64] Finished in 0.321 seconds with exit status 0 (successful).
INFO [73d459ca] Running /usr/bin/env mkdir -p ~/hacken-in-master/shared/log ~/hacken-in-master/shared/tmp/pids ~/hacken-in-master/shared/tmp/cache ~/hacken-in-master/shared/tmp/sockets ~/hacken-in-master/shared/public/system ~/hacken-in-master/shared/public/uploads ~/hacken-in-master/shared/public/assets as hacken@dubhe.uberspace.de
INFO [73d459ca] Finished in 0.502 seconds with exit status 0 (successful).
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `>=' for nil:NilClass

Tasks: TOP => deploy:set_previous_revision
(See full trace by running task with --trace)
The deploy has failed with an error: undefined method `>=' for nil:NilClass

Already up-to-date!
# HEAD detached at 633ee9a
nothing to commit, working directory clean
Dropped refs/stash@{0} (955a18cedc0aa91139e2ab3b9943d6660f8838ad)
Script failed with status 1
failed to deploy
```

Investigating.

**Comment by bascht** [comment]
Looks like `sshkit` broke (probably with 2.4.1?):

```
bascht at DevVm in ~/Code/hacken.in on master*                                                                                                  (1 job)
% bundle exec cap production deploy:set_previous_revision --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_previous_revision (first_time)
** Execute deploy:set_previous_revision
cap aborted!
NoMethodError: undefined method `>=' for nil:NilClass
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/formatters/pretty.rb:53:in `write_message'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/formatters/pretty.rb:21:in `log_command_start'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/backends/netssh.rb:84:in `execute_command'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `block in create_command_and_execute'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `tap'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `create_command_and_execute'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:50:in `test'
/tmp/deployment/ruby/2.4.0/gems/capistrano-3.4.0/lib/capistrano/tasks/deploy.rake:217:in `block (3 levels) in <top (required)>'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `run'
/tmp/deployment/ruby/2.4.0/gems/sshkit-1.9.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:set_previous_revision
```

The smelly bit:

```ruby
def write_message(verbosity, message, uuid=nil)
  original_output << "#{format_message(verbosity, message, uuid)}\n" if verbosity >= SSHKit.config.output_verbosity
end
```

**Comment by moonglum** [comment]
Thanks, @bascht <3 <3 <3

**Pull request merged**
