### PR TITLE
Bump Puppet to 4.x (will break all things)

### PR DESCRIPTION
**Pull request by bascht**
This will update the box puppet to 4.4.2 (and probably break some stuff, so just destroy + recreate the box).

### CODE REVIEW

**Comment by bascht** [comment]
@railsbros-dirk Can you re-test?

**Comment by bascht** [comment]
screenshot from 2016-04-28 13-28-11

Hashtag #worksforme.

**Comment by moonglum** [comment]
Ok, let's try that – you need to fix those Merge Conflicts first though 😄

**Comment by bascht** [comment]
@moonglum nah.

**Pull request closed without merging**
